[project]
name = "gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "karthik", email = "chukkakarthik1506@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
]

[project.scripts]
gpt = "gpt:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
